name: agl_flutter_voiceassistant
description: Offline voice assistant app designed for Automotive Grade Linux (AGL).

version: 0.0.1+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  grpc: ^3.2.3
  protobuf: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/agl_logo.png
    - assets/config.json