name: agl_flutter_voiceassistant
description: Offline voice assistant app designed for Automotive Grade Linux (AGL).

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  grpc: ^3.2.3
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/agl_logo.png
    - assets/config.json